# GitHub Pages Configuration
# Static site configuration - No Jekyll theme dependencies

# Site Settings
title: "Atikul Islam Rabbi - Social Media & Cybersecurity Expert | Founder of Cyber Infinity."
description: "Social Media & Cybersecurity Expert specializing in Recovering Hacked Facebook Page, Group, Account and other digital asset, Digital marketing strategy, and open-source contributions."
url: "https://atikulislamx.github.io/"
baseurl: "/AtikulIslam"

# Author Information
author:
  name: "Atikul Islam Rabbi"
  email: "help.atikulislam@gmail.com"
  twitter: "Atikulislamx"
  github: "Atikulislamx"
  linkedin: "Atikulislamx"
  website: "https://atikulislamx.github.io/Atikulislamx/"

# SEO and Meta Information
lang: en_US
timezone: Asia/Dhaka

# Site verification codes (add your verification codes here)
# google_site_verification: "your-google-verification-code"
# bing_site_verification: "your-bing-verification-code"

# Social Media Links
social_links:
  github: "https://github.com/Atikulislamx"
  linkedin: "https://linkedin.com/in/Atikulislamx"
  twitter: "https://twitter.com/Atikulislamx"
  youtube: "https://youtube.com/Atikulislamx"
  instagram: "https://instagram.com/Atikulislamx"
  facebook: "https://facebook.com/Atikulislamx"
  website: "https://atikulislamx.github.io/Atikulislamx/"
  email: "help.atikulislam@gmail.com"
  whatsapp: "https://wa.me/+8801300228105"

# Professional Information
professional:
  role: "Social Media and Cybersecurity Specialist."
  location: "Sirajganj, Bangladesh"
  experience_years: 5
  specializations:
    - "Recover Hacked Facebook Page"
    - "Recover Hacked Business Manager"
    - "AI Integration"
    - "Disabled Account Restoring"
    - "Open Source"

# Analytics and Tracking
# google_analytics: "G-XXXXXXXXXX"
# google_tag_manager: "GTM-XXXXXXX"

# GitHub Pages Build Settings
plugins: []

# File exclusions
exclude:
  - "node_modules/"
  - "*.log"
  - ".git/"
  - ".gitignore"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor/"

# Include static assets
include:
  - "images/"
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.png"
  - "*.ico"
  - "favicon.png"
